#!/bin/bash -e
#
# S2I run script for the 'springboot-sti' image.
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#


if [ -z "$TIMEZONE" ]; then
	echo "···································································································"
	echo "---->  VARIABLE TIMEZONE NO SETEADA - INICIANDO CON VALORES POR DEFECTO"
	echo "---->  POSIBLES VALORES: America/Montevideo | America/El_Salvador"
	echo "···································································································"
else
	echo "···································································································"
	echo "---->  TIMEZONE SETEADO ENCONTRADO: " $TIMEZONE
	echo "···································································································"
	cat /usr/share/zoneinfo/$TIMEZONE > /etc/localtime && \
	echo $TIMEZONE > /etc/timezone
fi



if [ ! -z "$WAITFOR_HOST" ] && [ ! -z "$WAITFOR_PORT" ] ; then
	echo "···································································································"
	echo "---->  WAITFOR  ACTIVADO.."
    until nc -z -v -w5 $WAITFOR_HOST $WAITFOR_PORT &> /dev/null; do echo waiting for $WAITFOR_HOST; sleep 15; done;	
	echo "···································································································"
fi


echo "INICIANDO ELASTICSEARCH.."

if [ $HOSTNAME == "elasticsearch-0" ]; then
export NUMBER1=1
export NUMBER2=2
fi

if [ $HOSTNAME == "elasticsearch-1" ]; then
export NUMBER1=0
export NUMBER2=2
fi

if [ $HOSTNAME == "elasticsearch-2" ]; then
export NUMBER1=0
export NUMBER2=1
fi

exec /opt/elasticsearch/bin//elasticsearch -E path.data=/opt/elasticsearch/data \
-E node.name=$HOSTNAME \
-E cluster.name=${CLUSTER_NAME:-openshift} \
-E bootstrap.memory_lock=true \
-E discovery.seed_hosts=elasticsearch-$NUMBER1,elasticsearch-$NUMBER2 \
-E cluster.initial_master_nodes=elasticsearch-0,elasticsearch-1,elasticsearch-2
